# Generated by Django 4.2.28 on 2026-02-05 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField(help_text='Award amount in USD')),
                ('deadline', models.DateField()),
                ('field_of_study', models.CharField(choices=[('All Fields', 'All Fields'), ('Engineering', 'Engineering'), ('Computer Science', 'Computer Science'), ('Business', 'Business'), ('Medicine', 'Medicine'), ('Arts', 'Arts & Humanities'), ('Science', 'Science'), ('Law', 'Law'), ('Education', 'Education')], default='All Fields', max_length=50)),
                ('scholarship_type', models.CharField(choices=[('Merit-Based', 'Merit-Based'), ('Need-Based', 'Need-Based'), ('Athletic', 'Athletic'), ('Diversity', 'Diversity & Inclusion')], default='Merit-Based', max_length=30)),
                ('student_status', models.CharField(choices=[('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('High School', 'High School')], default='Undergraduate', max_length=30)),
                ('min_gpa', models.DecimalField(decimal_places=1, default=0.0, max_digits=2)),
                ('eligibility', models.JSONField(blank=True, default=list)),
                ('benefits', models.JSONField(blank=True, default=list)),
                ('application_url', models.URLField(blank=True, default='#', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'scholarships',
                'ordering': ['-amount'],
            },
        ),
        migrations.CreateModel(
            name='SavedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='scholarships.scholarship')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
    ]
